Prevent fetching assets for `url(#ref)`
We've seen this error in the wild:

[HAPPO] Fetching asset from https://<redacted>/#shadow — storing as undefined
ArchiverError: entry name must be a non-empty string value
    at Archiver.append (/root/project/js/webapp/node_modules/archiver/lib/core.js:559:24)
    at /root/project/js/webapp/node_modules/happo-cypress/src/createAssetPackage.js:96:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 6)
    at async /root/project/js/webapp/node_modules/happo-cypress/src/createAssetPackage.js:104:5 {
  message: 'entry name must be a non-empty string value',
  code: 'ENTRYNAMEREQUIRED',

This error is causing happoTeardown to silently fail (times out after 1
min).

We can fix this by ignoring these asset urls.